`timescale 1ns / 1ps
///////////////////////////////////////////////////////////////////////////////
//
// Copyright yufei, UESTC 
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
///////////////////////////////////////////////////////////////////////////////
//-------------------------------------------------------------------------------------------
//
// Project    : Xcore LHB
// File       : Xcore_lhb_matrix_3x3.v
// Module     : Xcore_lhb_matrix_3x3()
// Dependancy : 
// Software   : python3.7, vivado2018.3
// Author     : Freddi Fu(yufei083X@gmail.com)
// Date       : 2022-10-27
// Version    : v1.0
// Description: LHB Matrix type.
//              This file is automatically generated by Limber LHB Generator.
//              Visit https://gitee.com/qyley/lhb for support
//              Bus information:
//              Master num: 3
//              Slave num: 3
//              Master connectivity:
//                  M0 : S0
//                  M1 : S0, S1, S2
//                  M2 : S0, S1
//              Slave Access:
//                  S0 : M2 > M0 > M1
//                  S1 : M2 > M1
//                  S2 : M1
//              Slave address/space:
//                  S0 : 32'h0000_0000 / 2^15 byte
//                  S1 : 32'h1000_0000 / 2^15 byte
//                  S2 : 32'h2000_0000 / 2^4 byte
//
//-------------------------------------------------------------------------------------------

module Xcore_lhb_matrix_3x3#(
    // parameters
    parameter DW = 32
)(
    input               i_clk,
    input               i_rst,  // high active
    // inlet req 0 (from master 0)
    input   [32-1:0]    i_m0_lhb_req_taddr,
    input   [DW-1:0]    i_m0_lhb_req_wdata,
    input   [3-1:0]     i_m0_lhb_req_tsize,
    input               i_m0_lhb_req_write,
    input               i_m0_lhb_req_valid,
    output              o_m0_lhb_req_ready,
    // inlet rsp 0 (to master 0)
    output  [DW-1:0]    o_m0_lhb_rsp_rdata,
    output              o_m0_lhb_rsp_error,
    output              o_m0_lhb_rsp_valid,
    input               i_m0_lhb_rsp_ready,
    // inlet req 1 (from master 1)
    input   [32-1:0]    i_m1_lhb_req_taddr,
    input   [DW-1:0]    i_m1_lhb_req_wdata,
    input   [3-1:0]     i_m1_lhb_req_tsize,
    input               i_m1_lhb_req_write,
    input               i_m1_lhb_req_valid,
    output              o_m1_lhb_req_ready,
    // inlet rsp 1 (to master 1)
    output  [DW-1:0]    o_m1_lhb_rsp_rdata,
    output              o_m1_lhb_rsp_error,
    output              o_m1_lhb_rsp_valid,
    input               i_m1_lhb_rsp_ready,
    // inlet req 2 (from master 2)
    input   [32-1:0]    i_m2_lhb_req_taddr,
    input   [DW-1:0]    i_m2_lhb_req_wdata,
    input   [3-1:0]     i_m2_lhb_req_tsize,
    input               i_m2_lhb_req_write,
    input               i_m2_lhb_req_valid,
    output              o_m2_lhb_req_ready,
    // inlet rsp 2 (to master 2)
    output  [DW-1:0]    o_m2_lhb_rsp_rdata,
    output              o_m2_lhb_rsp_error,
    output              o_m2_lhb_rsp_valid,
    input               i_m2_lhb_rsp_ready,
    // outlet req 0 (to slave 0)
    output  [32-1:0]    o_s0_lhb_req_taddr,
    output  [DW-1:0]    o_s0_lhb_req_wdata,
    output  [3-1:0]     o_s0_lhb_req_tsize,
    output              o_s0_lhb_req_write,
    output              o_s0_lhb_req_valid,
    input               i_s0_lhb_req_ready,
    // outlet rsp 0 (from slave 0)
    input   [DW-1:0]    i_s0_lhb_rsp_rdata,
    input               i_s0_lhb_rsp_error,
    input               i_s0_lhb_rsp_valid,
    output              o_s0_lhb_rsp_ready,
    // outlet req 1 (to slave 1)
    output  [32-1:0]    o_s1_lhb_req_taddr,
    output  [DW-1:0]    o_s1_lhb_req_wdata,
    output  [3-1:0]     o_s1_lhb_req_tsize,
    output              o_s1_lhb_req_write,
    output              o_s1_lhb_req_valid,
    input               i_s1_lhb_req_ready,
    // outlet rsp 1 (from slave 1)
    input   [DW-1:0]    i_s1_lhb_rsp_rdata,
    input               i_s1_lhb_rsp_error,
    input               i_s1_lhb_rsp_valid,
    output              o_s1_lhb_rsp_ready,
    // outlet req 2 (to slave 2)
    output  [32-1:0]    o_s2_lhb_req_taddr,
    output  [DW-1:0]    o_s2_lhb_req_wdata,
    output  [3-1:0]     o_s2_lhb_req_tsize,
    output              o_s2_lhb_req_write,
    output              o_s2_lhb_req_valid,
    input               i_s2_lhb_req_ready,
    // outlet rsp 2 (from slave 2)
    input   [DW-1:0]    i_s2_lhb_rsp_rdata,
    input               i_s2_lhb_rsp_error,
    input               i_s2_lhb_rsp_valid,
    output              o_s2_lhb_rsp_ready
);

    wire [32-1:0] mat_lhb_req_taddr_0_0;
    wire [DW-1:0] mat_lhb_req_wdata_0_0;
    wire [3-1:0] mat_lhb_req_tsize_0_0;
    wire mat_lhb_req_write_0_0;
    wire mat_lhb_req_valid_0_0;
    wire mat_lhb_req_ready_0_0;

    wire [DW-1:0] mat_lhb_rsp_rdata_0_0;
    wire mat_lhb_rsp_error_0_0;
    wire mat_lhb_rsp_valid_0_0;
    wire mat_lhb_rsp_ready_0_0;

    wire [32-1:0] mat_lhb_req_taddr_1_0;
    wire [DW-1:0] mat_lhb_req_wdata_1_0;
    wire [3-1:0] mat_lhb_req_tsize_1_0;
    wire mat_lhb_req_write_1_0;
    wire mat_lhb_req_valid_1_0;
    wire mat_lhb_req_ready_1_0;

    wire [DW-1:0] mat_lhb_rsp_rdata_1_0;
    wire mat_lhb_rsp_error_1_0;
    wire mat_lhb_rsp_valid_1_0;
    wire mat_lhb_rsp_ready_1_0;

    wire [32-1:0] mat_lhb_req_taddr_1_1;
    wire [DW-1:0] mat_lhb_req_wdata_1_1;
    wire [3-1:0] mat_lhb_req_tsize_1_1;
    wire mat_lhb_req_write_1_1;
    wire mat_lhb_req_valid_1_1;
    wire mat_lhb_req_ready_1_1;

    wire [DW-1:0] mat_lhb_rsp_rdata_1_1;
    wire mat_lhb_rsp_error_1_1;
    wire mat_lhb_rsp_valid_1_1;
    wire mat_lhb_rsp_ready_1_1;

    wire [32-1:0] mat_lhb_req_taddr_1_2;
    wire [DW-1:0] mat_lhb_req_wdata_1_2;
    wire [3-1:0] mat_lhb_req_tsize_1_2;
    wire mat_lhb_req_write_1_2;
    wire mat_lhb_req_valid_1_2;
    wire mat_lhb_req_ready_1_2;

    wire [DW-1:0] mat_lhb_rsp_rdata_1_2;
    wire mat_lhb_rsp_error_1_2;
    wire mat_lhb_rsp_valid_1_2;
    wire mat_lhb_rsp_ready_1_2;

    wire [32-1:0] mat_lhb_req_taddr_2_0;
    wire [DW-1:0] mat_lhb_req_wdata_2_0;
    wire [3-1:0] mat_lhb_req_tsize_2_0;
    wire mat_lhb_req_write_2_0;
    wire mat_lhb_req_valid_2_0;
    wire mat_lhb_req_ready_2_0;

    wire [DW-1:0] mat_lhb_rsp_rdata_2_0;
    wire mat_lhb_rsp_error_2_0;
    wire mat_lhb_rsp_valid_2_0;
    wire mat_lhb_rsp_ready_2_0;

    wire [32-1:0] mat_lhb_req_taddr_2_1;
    wire [DW-1:0] mat_lhb_req_wdata_2_1;
    wire [3-1:0] mat_lhb_req_tsize_2_1;
    wire mat_lhb_req_write_2_1;
    wire mat_lhb_req_valid_2_1;
    wire mat_lhb_req_ready_2_1;

    wire [DW-1:0] mat_lhb_rsp_rdata_2_1;
    wire mat_lhb_rsp_error_2_1;
    wire mat_lhb_rsp_valid_2_1;
    wire mat_lhb_rsp_ready_2_1;

    Xcore_lhb_matrix_simo_0 #(
        .DW(DW)
    ) inst_limber_lhb_matrix_simo_0 (
        .i_clk              (i_clk),
        .i_rst              (i_rst),
        .i_m0_lhb_req_taddr (i_m0_lhb_req_taddr),
        .i_m0_lhb_req_wdata (i_m0_lhb_req_wdata),
        .i_m0_lhb_req_tsize (i_m0_lhb_req_tsize),
        .i_m0_lhb_req_write (i_m0_lhb_req_write),
        .i_m0_lhb_req_valid (i_m0_lhb_req_valid),
        .o_m0_lhb_req_ready (o_m0_lhb_req_ready),
        .o_m0_lhb_rsp_rdata (o_m0_lhb_rsp_rdata),
        .o_m0_lhb_rsp_error (o_m0_lhb_rsp_error),
        .o_m0_lhb_rsp_valid (o_m0_lhb_rsp_valid),
        .i_m0_lhb_rsp_ready (i_m0_lhb_rsp_ready),
        .o_s0_lhb_req_taddr (mat_lhb_req_taddr_0_0),
        .o_s0_lhb_req_wdata (mat_lhb_req_wdata_0_0),
        .o_s0_lhb_req_tsize (mat_lhb_req_tsize_0_0),
        .o_s0_lhb_req_write (mat_lhb_req_write_0_0),
        .o_s0_lhb_req_valid (mat_lhb_req_valid_0_0),
        .i_s0_lhb_req_ready (mat_lhb_req_ready_0_0),
        .i_s0_lhb_rsp_rdata (mat_lhb_rsp_rdata_0_0),
        .i_s0_lhb_rsp_error (mat_lhb_rsp_error_0_0),
        .i_s0_lhb_rsp_valid (mat_lhb_rsp_valid_0_0),
        .o_s0_lhb_rsp_ready (mat_lhb_rsp_ready_0_0)
    );

    Xcore_lhb_matrix_simo_1 #(
        .DW(DW)
    ) inst_limber_lhb_matrix_simo_1 (
        .i_clk              (i_clk),
        .i_rst              (i_rst),
        .i_m0_lhb_req_taddr (i_m1_lhb_req_taddr),
        .i_m0_lhb_req_wdata (i_m1_lhb_req_wdata),
        .i_m0_lhb_req_tsize (i_m1_lhb_req_tsize),
        .i_m0_lhb_req_write (i_m1_lhb_req_write),
        .i_m0_lhb_req_valid (i_m1_lhb_req_valid),
        .o_m0_lhb_req_ready (o_m1_lhb_req_ready),
        .o_m0_lhb_rsp_rdata (o_m1_lhb_rsp_rdata),
        .o_m0_lhb_rsp_error (o_m1_lhb_rsp_error),
        .o_m0_lhb_rsp_valid (o_m1_lhb_rsp_valid),
        .i_m0_lhb_rsp_ready (i_m1_lhb_rsp_ready),
        .o_s0_lhb_req_taddr (mat_lhb_req_taddr_1_0),
        .o_s0_lhb_req_wdata (mat_lhb_req_wdata_1_0),
        .o_s0_lhb_req_tsize (mat_lhb_req_tsize_1_0),
        .o_s0_lhb_req_write (mat_lhb_req_write_1_0),
        .o_s0_lhb_req_valid (mat_lhb_req_valid_1_0),
        .i_s0_lhb_req_ready (mat_lhb_req_ready_1_0),
        .i_s0_lhb_rsp_rdata (mat_lhb_rsp_rdata_1_0),
        .i_s0_lhb_rsp_error (mat_lhb_rsp_error_1_0),
        .i_s0_lhb_rsp_valid (mat_lhb_rsp_valid_1_0),
        .o_s0_lhb_rsp_ready (mat_lhb_rsp_ready_1_0),
        .o_s1_lhb_req_taddr (mat_lhb_req_taddr_1_1),
        .o_s1_lhb_req_wdata (mat_lhb_req_wdata_1_1),
        .o_s1_lhb_req_tsize (mat_lhb_req_tsize_1_1),
        .o_s1_lhb_req_write (mat_lhb_req_write_1_1),
        .o_s1_lhb_req_valid (mat_lhb_req_valid_1_1),
        .i_s1_lhb_req_ready (mat_lhb_req_ready_1_1),
        .i_s1_lhb_rsp_rdata (mat_lhb_rsp_rdata_1_1),
        .i_s1_lhb_rsp_error (mat_lhb_rsp_error_1_1),
        .i_s1_lhb_rsp_valid (mat_lhb_rsp_valid_1_1),
        .o_s1_lhb_rsp_ready (mat_lhb_rsp_ready_1_1),
        .o_s2_lhb_req_taddr (mat_lhb_req_taddr_1_2),
        .o_s2_lhb_req_wdata (mat_lhb_req_wdata_1_2),
        .o_s2_lhb_req_tsize (mat_lhb_req_tsize_1_2),
        .o_s2_lhb_req_write (mat_lhb_req_write_1_2),
        .o_s2_lhb_req_valid (mat_lhb_req_valid_1_2),
        .i_s2_lhb_req_ready (mat_lhb_req_ready_1_2),
        .i_s2_lhb_rsp_rdata (mat_lhb_rsp_rdata_1_2),
        .i_s2_lhb_rsp_error (mat_lhb_rsp_error_1_2),
        .i_s2_lhb_rsp_valid (mat_lhb_rsp_valid_1_2),
        .o_s2_lhb_rsp_ready (mat_lhb_rsp_ready_1_2)
    );

    Xcore_lhb_matrix_simo_2 #(
        .DW(DW)
    ) inst_limber_lhb_matrix_simo_2 (
        .i_clk              (i_clk),
        .i_rst              (i_rst),
        .i_m0_lhb_req_taddr (i_m2_lhb_req_taddr),
        .i_m0_lhb_req_wdata (i_m2_lhb_req_wdata),
        .i_m0_lhb_req_tsize (i_m2_lhb_req_tsize),
        .i_m0_lhb_req_write (i_m2_lhb_req_write),
        .i_m0_lhb_req_valid (i_m2_lhb_req_valid),
        .o_m0_lhb_req_ready (o_m2_lhb_req_ready),
        .o_m0_lhb_rsp_rdata (o_m2_lhb_rsp_rdata),
        .o_m0_lhb_rsp_error (o_m2_lhb_rsp_error),
        .o_m0_lhb_rsp_valid (o_m2_lhb_rsp_valid),
        .i_m0_lhb_rsp_ready (i_m2_lhb_rsp_ready),
        .o_s0_lhb_req_taddr (mat_lhb_req_taddr_2_0),
        .o_s0_lhb_req_wdata (mat_lhb_req_wdata_2_0),
        .o_s0_lhb_req_tsize (mat_lhb_req_tsize_2_0),
        .o_s0_lhb_req_write (mat_lhb_req_write_2_0),
        .o_s0_lhb_req_valid (mat_lhb_req_valid_2_0),
        .i_s0_lhb_req_ready (mat_lhb_req_ready_2_0),
        .i_s0_lhb_rsp_rdata (mat_lhb_rsp_rdata_2_0),
        .i_s0_lhb_rsp_error (mat_lhb_rsp_error_2_0),
        .i_s0_lhb_rsp_valid (mat_lhb_rsp_valid_2_0),
        .o_s0_lhb_rsp_ready (mat_lhb_rsp_ready_2_0),
        .o_s1_lhb_req_taddr (mat_lhb_req_taddr_2_1),
        .o_s1_lhb_req_wdata (mat_lhb_req_wdata_2_1),
        .o_s1_lhb_req_tsize (mat_lhb_req_tsize_2_1),
        .o_s1_lhb_req_write (mat_lhb_req_write_2_1),
        .o_s1_lhb_req_valid (mat_lhb_req_valid_2_1),
        .i_s1_lhb_req_ready (mat_lhb_req_ready_2_1),
        .i_s1_lhb_rsp_rdata (mat_lhb_rsp_rdata_2_1),
        .i_s1_lhb_rsp_error (mat_lhb_rsp_error_2_1),
        .i_s1_lhb_rsp_valid (mat_lhb_rsp_valid_2_1),
        .o_s1_lhb_rsp_ready (mat_lhb_rsp_ready_2_1)
    );

    Xcore_lhb_matrix_miso_0 #(
        .DW(DW),
        .RR(0)
    ) inst_llimber_lhb_matrix_miso_0 (
        .i_clk              (i_clk),
        .i_rst              (i_rst),
        .i_m0_lhb_req_taddr (mat_lhb_req_taddr_2_0),
        .i_m0_lhb_req_wdata (mat_lhb_req_wdata_2_0),
        .i_m0_lhb_req_tsize (mat_lhb_req_tsize_2_0),
        .i_m0_lhb_req_write (mat_lhb_req_write_2_0),
        .i_m0_lhb_req_valid (mat_lhb_req_valid_2_0),
        .o_m0_lhb_req_ready (mat_lhb_req_ready_2_0),
        .o_m0_lhb_rsp_rdata (mat_lhb_rsp_rdata_2_0),
        .o_m0_lhb_rsp_error (mat_lhb_rsp_error_2_0),
        .o_m0_lhb_rsp_valid (mat_lhb_rsp_valid_2_0),
        .i_m0_lhb_rsp_ready (mat_lhb_rsp_ready_2_0),
        .i_m1_lhb_req_taddr (mat_lhb_req_taddr_0_0),
        .i_m1_lhb_req_wdata (mat_lhb_req_wdata_0_0),
        .i_m1_lhb_req_tsize (mat_lhb_req_tsize_0_0),
        .i_m1_lhb_req_write (mat_lhb_req_write_0_0),
        .i_m1_lhb_req_valid (mat_lhb_req_valid_0_0),
        .o_m1_lhb_req_ready (mat_lhb_req_ready_0_0),
        .o_m1_lhb_rsp_rdata (mat_lhb_rsp_rdata_0_0),
        .o_m1_lhb_rsp_error (mat_lhb_rsp_error_0_0),
        .o_m1_lhb_rsp_valid (mat_lhb_rsp_valid_0_0),
        .i_m1_lhb_rsp_ready (mat_lhb_rsp_ready_0_0),
        .i_m2_lhb_req_taddr (mat_lhb_req_taddr_1_0),
        .i_m2_lhb_req_wdata (mat_lhb_req_wdata_1_0),
        .i_m2_lhb_req_tsize (mat_lhb_req_tsize_1_0),
        .i_m2_lhb_req_write (mat_lhb_req_write_1_0),
        .i_m2_lhb_req_valid (mat_lhb_req_valid_1_0),
        .o_m2_lhb_req_ready (mat_lhb_req_ready_1_0),
        .o_m2_lhb_rsp_rdata (mat_lhb_rsp_rdata_1_0),
        .o_m2_lhb_rsp_error (mat_lhb_rsp_error_1_0),
        .o_m2_lhb_rsp_valid (mat_lhb_rsp_valid_1_0),
        .i_m2_lhb_rsp_ready (mat_lhb_rsp_ready_1_0),
        .o_s0_lhb_req_taddr (o_s0_lhb_req_taddr),
        .o_s0_lhb_req_wdata (o_s0_lhb_req_wdata),
        .o_s0_lhb_req_tsize (o_s0_lhb_req_tsize),
        .o_s0_lhb_req_write (o_s0_lhb_req_write),
        .o_s0_lhb_req_valid (o_s0_lhb_req_valid),
        .i_s0_lhb_req_ready (i_s0_lhb_req_ready),
        .i_s0_lhb_rsp_rdata (i_s0_lhb_rsp_rdata),
        .i_s0_lhb_rsp_error (i_s0_lhb_rsp_error),
        .i_s0_lhb_rsp_valid (i_s0_lhb_rsp_valid),
        .o_s0_lhb_rsp_ready (o_s0_lhb_rsp_ready)
    );

    Xcore_lhb_matrix_miso_1 #(
        .DW(DW),
        .RR(0)
    ) inst_llimber_lhb_matrix_miso_1 (
        .i_clk              (i_clk),
        .i_rst              (i_rst),
        .i_m0_lhb_req_taddr (mat_lhb_req_taddr_2_1),
        .i_m0_lhb_req_wdata (mat_lhb_req_wdata_2_1),
        .i_m0_lhb_req_tsize (mat_lhb_req_tsize_2_1),
        .i_m0_lhb_req_write (mat_lhb_req_write_2_1),
        .i_m0_lhb_req_valid (mat_lhb_req_valid_2_1),
        .o_m0_lhb_req_ready (mat_lhb_req_ready_2_1),
        .o_m0_lhb_rsp_rdata (mat_lhb_rsp_rdata_2_1),
        .o_m0_lhb_rsp_error (mat_lhb_rsp_error_2_1),
        .o_m0_lhb_rsp_valid (mat_lhb_rsp_valid_2_1),
        .i_m0_lhb_rsp_ready (mat_lhb_rsp_ready_2_1),
        .i_m1_lhb_req_taddr (mat_lhb_req_taddr_1_1),
        .i_m1_lhb_req_wdata (mat_lhb_req_wdata_1_1),
        .i_m1_lhb_req_tsize (mat_lhb_req_tsize_1_1),
        .i_m1_lhb_req_write (mat_lhb_req_write_1_1),
        .i_m1_lhb_req_valid (mat_lhb_req_valid_1_1),
        .o_m1_lhb_req_ready (mat_lhb_req_ready_1_1),
        .o_m1_lhb_rsp_rdata (mat_lhb_rsp_rdata_1_1),
        .o_m1_lhb_rsp_error (mat_lhb_rsp_error_1_1),
        .o_m1_lhb_rsp_valid (mat_lhb_rsp_valid_1_1),
        .i_m1_lhb_rsp_ready (mat_lhb_rsp_ready_1_1),
        .o_s0_lhb_req_taddr (o_s1_lhb_req_taddr),
        .o_s0_lhb_req_wdata (o_s1_lhb_req_wdata),
        .o_s0_lhb_req_tsize (o_s1_lhb_req_tsize),
        .o_s0_lhb_req_write (o_s1_lhb_req_write),
        .o_s0_lhb_req_valid (o_s1_lhb_req_valid),
        .i_s0_lhb_req_ready (i_s1_lhb_req_ready),
        .i_s0_lhb_rsp_rdata (i_s1_lhb_rsp_rdata),
        .i_s0_lhb_rsp_error (i_s1_lhb_rsp_error),
        .i_s0_lhb_rsp_valid (i_s1_lhb_rsp_valid),
        .o_s0_lhb_rsp_ready (o_s1_lhb_rsp_ready)
    );

    Xcore_lhb_matrix_miso_2 #(
        .DW(DW),
        .RR(0)
    ) inst_llimber_lhb_matrix_miso_2 (
        .i_clk              (i_clk),
        .i_rst              (i_rst),
        .i_m0_lhb_req_taddr (mat_lhb_req_taddr_1_2),
        .i_m0_lhb_req_wdata (mat_lhb_req_wdata_1_2),
        .i_m0_lhb_req_tsize (mat_lhb_req_tsize_1_2),
        .i_m0_lhb_req_write (mat_lhb_req_write_1_2),
        .i_m0_lhb_req_valid (mat_lhb_req_valid_1_2),
        .o_m0_lhb_req_ready (mat_lhb_req_ready_1_2),
        .o_m0_lhb_rsp_rdata (mat_lhb_rsp_rdata_1_2),
        .o_m0_lhb_rsp_error (mat_lhb_rsp_error_1_2),
        .o_m0_lhb_rsp_valid (mat_lhb_rsp_valid_1_2),
        .i_m0_lhb_rsp_ready (mat_lhb_rsp_ready_1_2),
        .o_s0_lhb_req_taddr (o_s2_lhb_req_taddr),
        .o_s0_lhb_req_wdata (o_s2_lhb_req_wdata),
        .o_s0_lhb_req_tsize (o_s2_lhb_req_tsize),
        .o_s0_lhb_req_write (o_s2_lhb_req_write),
        .o_s0_lhb_req_valid (o_s2_lhb_req_valid),
        .i_s0_lhb_req_ready (i_s2_lhb_req_ready),
        .i_s0_lhb_rsp_rdata (i_s2_lhb_rsp_rdata),
        .i_s0_lhb_rsp_error (i_s2_lhb_rsp_error),
        .i_s0_lhb_rsp_valid (i_s2_lhb_rsp_valid),
        .o_s0_lhb_rsp_ready (o_s2_lhb_rsp_ready)
    );

endmodule
